apiVersion: v1
kind: Service
metadata:
  name: tare-backend-service
spec:
  selector:
    app: tare-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
